services:
  db:
    container_name: db_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_config:/var/lib/pgadmin:rw
    depends_on:
      - db
  taxi_ingest:
    container_name: taxi_ingest
    build:
      context: ./taxi_ingest
      dockerfile: taxi_ingest.Dockerfile
    volumes:
      - ./taxi_ingest:/workspace
    command: sleep infinity
    depends_on:
      - db